export const CHANGE_INPUT_FIELD = 'CHANGE_SEARCH_FIELD';
export const CHANGE_INPUT_FIELD_SUCCESS = 'CHANGE_SEARCH_FIELD_SUCCESS';
export const REQUEST_IO_PENDING = 'REQUESTS_IO_PENDING';
export const REQUEST_IO_SUCCESS = 'REQUESTS_IO_SUCCESS';
export const REQUEST_IO_FAILED = 'REQUESTS_IO_FAILED';
